### ISSUE TITLE
Issue Rendering the Sae Input Component

### ISSUE THREAD

**Issue by aaronminkov** [halilb/react-native-textinput-effects#103]
After properly importing the react-native-textinput-effects module and including <Sae /> in my code, I run into the error:

TypeError: undefined is not an object (evaluating 'Component.propTypes')

Code:
`import React, {Component} from 'react'';
import { View } from 'react-native';
import { Sae } from 'react-native-textinput-effects';

export default class App extends React.Component {
    render() {
        return (
             <View>
                  <Sae />
              </View>
         )
     }
}`

What could be causing this issue?

**Comment by xuananpham93** [comment]
Did you solve the issue?

**Comment by pulpdood** [comment]
Getting this issue as well

**Comment by pulpdood** [comment]
Try doing an npm install prop-types and it seems to be working now. Also make sure all required props are passed in
