### ISSUE TITLE
Cannot Mask Input with react-native-masked-text

### ISSUE THREAD

**Issue by lgahdl** [halilb/react-native-textinput-effects#106]
i'm using Fumi to take the phone number, and its incompatible with TextInputMask from react-native-masked-text, there's a way that i don't know to mask input and make it appears like "(99) 99999-9999"?

**Comment by halilb** [comment]
We don't have a built-in support for that @lgahdl. I believe you can achieve a similar thing by manipulating the value you're passing to the TextInput.
