### ISSUE TITLE
componentWillReceiveProps is not secure anymore

### ISSUE THREAD

**Issue by apppro123** [halilb/react-native-textinput-effects#108]
I got a warning because of this methode "componentWillReceiveProps" in lib/BaseInput.js.

I made now a workaround with shouldComponentUpdate (i know that this is propably not the best solution):

Instead of componentWillReceiveProps(...){...}

I now use shouldComponentUpdate(newProps){...
return true}

I always return true now, so it definitely updates, i'm not sure if this is needed...
I hope this helps in improving your amazing library.
Thanks for your work in making these effects!

If there are further questions, just write please.

**Comment by rotobogdan** [comment]
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Same here

**Comment by mrousavy** [comment]
@apppro123 would you mind creating a pull request with your proposed solution?

**Comment by halilb** [comment]
This is fixed with version `0.6.1`.
