### ISSUE TITLE
ExceptionsManager.js:126 Warning: Failed prop type: The prop `iconClass` is marked as required in `Sae`, but its value is `undefined`.

### ISSUE THREAD

**Issue by andyliuzs** [halilb/react-native-textinput-effects#115]
ExceptionsManager.js:126 Warning: Failed prop type: The prop `iconClass` is marked as required in `Sae`, but its value is `undefined`.

**Comment by halilb** [comment]
Sounds like you are not passing `iconClass` prop but it's required for that. Could you post your full code?
