### ISSUE TITLE
Make input type password 

### ISSUE THREAD

**Issue by m-arslan01** [halilb/react-native-textinput-effects#116]
I am having issue by making the input type to password . I am using Fumi component from your package.

<Fumi
           label={'Enter password'}
           iconClass={FontAwesomeIcon}
           iconName={'key'}
           iconColor={'#808080'}
           iconSize={20}
           iconWidth={40}
           inputPadding={16}
           onChangeText={(password) => setpassword(password)}
        />

**Comment by halilb** [comment]
It is handled by `react-native`  and you can achieve that by passing `secureTextEntry={true}` prop to any TextInput component. Please checkout https://reactnative.dev/docs/textinput#securetextentry
