### ISSUE TITLE
Text Inputs with border radius.

### ISSUE THREAD

**Issue by rohitpotato** [halilb/react-native-textinput-effects#117]
After examining the code, it is safe to say that border-radius is not applied to any of the components. Anyway to achieve this?

**Comment by halilb** [comment]
It is possible for some of the inputs actually by passing it through `style` prop. It worked for Fumi:

```
        <Fumi
          style={{
            borderRadius: 8,
          }}
          label={"Course Name"}
          labelStyle={{ color: "#a3a3a3" }}
          inputStyle={{ color: "#f95a25" }}
          iconClass={FontAwesomeIcon}
          iconName={"university"}
          iconColor={"#f95a25"}
          iconSize={15}
        />
```

<img width="415" alt="Screen Shot 2020-04-26 at 22 04 44" src="https://user-images.githubusercontent.com/2227041/80317018-f1246980-8809-11ea-82c1-49e2df2a4599.png">

I believe some other inputs doesn't support it as you said. The best option would be fork the repo and make custom changes on them. Please let me know if you need any assistance on that.
