### ISSUE TITLE
Components wont display in RN 0.36

### ISSUE THREAD

**Issue by jjdp** [halilb/react-native-textinput-effects#14]
see https://github.com/facebook/react-native/commit/0a9b6bedb312eba22c5bc11498b1cc41363e5f27

**Comment by florianbepunkt** [comment]
+1

**Comment by halilb** [comment]
Thanks for reporting @jjdp and @florianbepunkt!

I just upgraded the example project to RN 0.36.1 but couldn't reproduce the problem. Could you guys try updating the example project and give it a try again?

**Comment by florianbepunkt** [comment]
I will try and check on the weekend. Curious why you couldn't reproduce this… can you share some more specs of your test? I had a fresh install of react native cli from yesterday, but had to create a project react-native version 0.36.1 due to some dependecy issues.

**Comment by halilb** [comment]
I just used the example project inside this repository. It's currently using 0.36.1, so you can simply clone the repo and try it out with that project.

**Comment by jjdp** [comment]
weird. hideo is the only one that isn't displaying

**Comment by halilb** [comment]
@jjdp Can you check out the example project? Hideo is displayed even if it's parent doesn't have `flex: 1`.

**Comment by jjdp** [comment]
i guess its probably because of my nested views with so many `flex:1`. it works if i set a `width` and `height`.

**Comment by halilb** [comment]
This shouldn't be a problem with newer react native releases.
