### ISSUE TITLE
Icon viewConfig is not defined

### ISSUE THREAD

**Issue by jjhesk** [halilb/react-native-textinput-effects#16]
I have encountered this 
 "react-native-textinput-effects": "0.2.0",

   "react": "15.3.2",
    "react-native": "0.37.0",

**Comment by halilb** [comment]
Thanks for reporting @jjhesk. This is a duplicate issue. You can see my explanation from https://github.com/halilb/react-native-textinput-effects/issues/15#issuecomment-261875257
