### ISSUE TITLE
Ref props of text input does not work

### ISSUE THREAD

**Issue by Talkwondo** [halilb/react-native-textinput-effects#17]
Hello,
This is my code from textinput component:
<TextInput
              placeholder="Residence"
              ref={(ref) => this._residenceRef = ref}
              placeholderTextColor="rgba(0,0,0,0.2)"
              keyboardType="email-address"
              selectionColor="#61448D"
              style={styles.input}
              autoCapitalize="none"
              autoCorrect={false}
              onChangeText={(residence) => this.residence = residence}
              returnKeyType="next"
              onSubmitEditing={() => this._emailRef.focus()}
              />
I changed the textinput to Kohana but the ref doesn't work.
<Kohana
            ref={(ref) => this._emailRef = ref}           
            style={{
              flex: 1,
              height: 45,
              backgroundColor: "rgba(0,0,0,0)",
              padding: 10}}
            onChangeText={(email) => this.email = email}
            returnKeyType="next"
            onSubmitEditing={() => this._passwordRef.focus()}
            label={'Email'}
            iconClass={MaterialsIcon}
            iconName={'email'}
            iconColor={'#61448D'}
            labelStyle={{ color: 'rgba(0,0,0,0.2)' }}
            inputStyle={{ color: "rgba(0,0,0,0.2)"}}
            />
Please help.

Thanks,

**Comment by grundmanise** [comment]
Same here. We should have the ability to pass refs down to the textInput.

**Comment by mxmtsk** [comment]
+1

**Comment by jjdp** [comment]
+1

**Comment by MarlBurroW** [comment]
+1

**Comment by rstegg** [comment]
you can find all exposed methods here: https://github.com/halilb/react-native-textinput-effects/blob/master/lib/BaseInput.js

so call ref._focus() not ref.focus() 

its probably not the best to not refer to public methods in a private method syntax, but it's a great library.

**Comment by halilb** [comment]
Thanks for reporting guys!

I've added some public methods into BaseInput that calls inner TextInput's methods. You can now call `focus`, `blur`, `isFocused` and `clear` methods directly.

I also added `inputRef` method to get the inner TextInput ref. So you can also use that method to retrieve the inner input ref and make a method call.

```
// those calls have equal results
this.refs.kohana.focus();
this.refs.kohana.inputRef().focus();
```

Please test this using 0.3.0 release and let me know if anything goes wrong.
