### ISSUE TITLE
Make the Padding configurable for better styling

### ISSUE THREAD

**Issue by lakhman** [halilb/react-native-textinput-effects#18]
Hi,

Great lib, can we make the padding and label height a prop so the user can configure the styling to their needs?

https://github.com/halilb/react-native-textinput-effects/blob/master/lib/Madoka.js#L12-L13
https://github.com/halilb/react-native-textinput-effects/blob/master/lib/Sae.js#L12-L13

The same goes for `fontSize`, I tried to pass it via a prop, but this is not possible as when merged is overridden.

https://github.com/halilb/react-native-textinput-effects/blob/master/lib/Madoka.js#L118-L121

The ability to style things more would be awesome.
Thanks!

**Comment by luco** [comment]
+1 on this. Had to modify directly into node_modules.

**Comment by halilb** [comment]
Finally fixed with 9801f4b.
