### ISSUE TITLE
Change height of the textInput

### ISSUE THREAD

**Issue by grundmanise** [halilb/react-native-textinput-effects#19]
Hi, thanks for this amazing component! 
Is it possible to change textInput height? I am using multiline={true} and would like to set height 2 times bigger than the current height for Hoshi.

**Comment by oleksiykh** [comment]
Same here, or even better can we get the support for multiline? Auto adjust the box as it goes to the next line :)

**Comment by gotoAndBliss** [comment]
+1

**Comment by alexhhn** [comment]
+1

**Comment by ykcai** [comment]
+1 would love to have multiline support

**Comment by tudoanh** [comment]
It'd be so nice to support multipleline. 
Love this lib btw.

**Comment by yash2code** [comment]
same, how to adjust height ? anyone able to resolved this?

**Comment by yash2code** [comment]
Only one solution found: 

Goto the file (for eg. kaede.js if you are using kaede) in node modules, change height from there !

**Comment by rochapablo** [comment]
+1

**Comment by rochapablo** [comment]
I don't know what I was doing wrong, because I though had tried everything. But now I made it!

```
<Hideo
            iconSize={HideoStyle.size.icon}
            height={HideoStyle.size.input}
            inputStyle={[HideoStyle.input]}
            style={HideoStyle.container}
          />
```

```
const height = 37;

HideoStyle = {
    container: {
        marginVertical: 5, 
        borderRadius: 4,
        borderStyle: 'solid',
        borderWidth: 2,
        borderColor: Color.mercury,
        backgroundColor: Color.white,
        flex: 0,
        height: 'auto',
        overflow: 'hidden'
    },
    input: {
        height: height,
        backgroundColor: Color.white,
        fontWeight: '600',
        fontSize: 11,
    },
    size: {
        input: height,
        icon: 20
    }
}
```

**Comment by DavidTatis** [comment]
if you want to change height, fontSize, Color, etc. you can go to: node_modules/react-native-textinput-effects\lib, open the .JS file effect you are using, for example Hoshi.js. There you can edit the styles.
for example Hoshi.js:
```
const styles = StyleSheet.create({
  container: {
    borderBottomWidth: 2,
    borderBottomColor: '#b9c1ca',
  },
  labelContainer: {
    position: 'absolute',
  },
  label: {
    fontSize: 20,
    color: '#000000',
  },
```

**Comment by halilb** [comment]
There isn't a generic solution I can apply for all components for changing the height as it's highly coupled with the animation. And changing input height would break some of those animations.

So I suggest forking the repository and applying your customizations directly on the input to make it work without breaking the animation.
