### ISSUE TITLE
Feature Request : Disabled Mode

### ISSUE THREAD

**Issue by etaiklein** [halilb/react-native-textinput-effects#20]
I want to use RNTIE to display a time. 

However, I don't want the user to edit the time directly. I want the user's clicking RNTIE to open a time picker dialogue instead. I want the text-editing part of the component to be disabled.

Ideally, it would look something like this.
```html
<TouchableOpacity onPress={openTimeDialogue}>
  <Fumi
    label={'time'}
    iconClass={Icon}
    iconName={'bell'}
    iconColor={colors.primary}

    disabled={true} //NEW
    value={toTimeString(this.props.time)}
  />
</TouchableOpacity>
```

Here is the current behavior
![](http://g.recordit.co/SvuYEPrRit.gif)

**Comment by halilb** [comment]
Thanks for reporting @etaiklein!

I just tested TextInput's `editable` prop and I think that's what you're looking for. Can you give it a try?

```
<TouchableOpacity onPress={openTimeDialogue}>
  <Fumi
    label={'time'}
    iconClass={Icon}
    iconName={'bell'}
    iconColor={colors.primary}
    value={toTimeString(this.props.time)}
    editable={false}
  />
</TouchableOpacity>
```

**Comment by etaiklein** [comment]
Editable doesn't seem to have an effect. 
The gif was from [my latest build](https://github.com/etaiklein/wandr/blob/master/app/components/welcome/index.js#L146) which is already using `editable={false}`

**Comment by halilb** [comment]
This should be fixed with the latest package @etaiklein. Thanks for reporting!
