### ISSUE TITLE
Feature Request: Autocomplete

### ISSUE THREAD

**Issue by JozefCipa** [halilb/react-native-textinput-effects#23]
Hi guys,
What about implementing autocomplete support?

**Comment by jonathanpalma** [comment]
Any news about this?

**Comment by halilb** [comment]
Thanks for reporting @JozefCipa!

I just checked out UI and UX designs for auto complete out there, and I think it's hard to create a generic and good looking auto complete feature in the library.

So I won't be able to implement this feature but I'm open for PRs that can deliver good looking and generic solutions here.
