### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by mybigman** [halilb/react-native-textinput-effects#25]
Hello there,

I am using macbook and Genymotion.

When I add say the FUMI component to my APP my CPU usage is  nearly 100% under the Genymotion player, as soon as I remove the component and add a standard one the CPU usage drops completely.

Any ideas?

**Comment by halilb** [comment]
I'm so sorry for my late answer @mybigman. I just tried this on a real device and can't reproduce it.

I'm not an expert about android, but is it possible this is an emulator problem? Coıld you re-test this on a real device? Please re-open the issue if you're still experiencing the problem on a device.
