### ISSUE TITLE
how to get input text value?

### ISSUE THREAD

**Issue by aqnaruto** [halilb/react-native-textinput-effects#26]
thankyou your amazing effects.
but,how to get the  input value,  it is confused me .
i wish could have function like this `onTextChange={(value)=>{...}}`

**Comment by DarkHollow** [comment]
You can do it like a normal `TextInput`.
For example:

```javascript
onChangeText={ (text) => {this.setState({textValue: text}) }
```

**Comment by jjhesk** [comment]
please add this to the note in the README

**Comment by halilb** [comment]
Thanks for the explanation @DarkHollow.

I added an example that shows using default TextInput props to the README.
