### ISSUE TITLE
the HoshiInput's tail is beyond the border in iOS 

### ISSUE THREAD

**Issue by iOSQiao** [halilb/react-native-textinput-effects#3]
I use Hoshi follow the example,but the HoshiInput's tail is beyond the border,can you help me?
My email is 642742500@qq.com. Thank you!

**Comment by halilb** [comment]
Thanks for reporting @iOSQiao.

Do you have any sample code for me to regenerate the problem here?

**Comment by iOSQiao** [comment]
Yes, I have. But I need to send the sample code for you at night. Because the sample code on my computer.
I will contact you tonight. Thank you @Halil Bilir 




------------------ 原始邮件 ------------------
发件人: "Halil Bilir";<notifications@github.com>;
发送时间: 2016年7月21日(星期四) 凌晨3:47
收件人: "halilb/react-native-textinput-effects"<react-native-textinput-effects@noreply.github.com>; 
抄送: "iOSQiao"<642742500@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [halilb/react-native-textinput-effects] the HoshiInput's tail isbeyond the border in iOS (#3)




Thanks for reporting @iOSQiao.
 
Do you have any sample code for me to regenerate the problem here?

**Comment by halilb** [comment]
Ping @iOSQiao.

**Comment by halilb** [comment]
Closing for the inactivity. Let me know if you still experience the problem!

**Comment by shuiRong** [comment]
@halilb 
I think I get the same problem. Here's some information:
```
react-native-textinput-effects@^0.4.2
react-native@0.57.1

// sample code
<View style={{ backgroundColor: color.white }}>
    <Hoshi label={'Town'} borderColor={'#b76c94'} />
    <Hoshi style={styles.input} label={'Street'} borderColor={'#7ac1ba'} />
</View>

```

**Your need to see clearly**

![image](https://user-images.githubusercontent.com/16076993/51112500-d3600a80-1839-11e9-9fa6-bbd75621ea2e.png)

If you need more information, let me know.

**Comment by Osamasomy** [comment]
> @halilb Thanks for your component, It's great!
> 
> And I think I get the same problem. Here's some information:
> 
> ```
> Android6.0.1
> Redmi Note3
> 
> // build.grade
> ext {
>         buildToolsVersion = "28.0.0"
>         minSdkVersion = 16
>         compileSdkVersion = 28
>         targetSdkVersion = 28
>         supportLibVersion = "28.0.0"
>  }
> 
> 
> react-native-textinput-effects@^0.4.2
> react-native@0.57.1
> 
> // sample code
> <View style={{ backgroundColor: color.white }}>
>     <Hoshi label={'Town'} borderColor={'#b76c94'} />
>     <Hoshi style={styles.input} label={'Street'} borderColor={'#7ac1ba'} />
> </View>
> ```
> 
> ![image](https://user-images.githubusercontent.com/16076993/51112500-d3600a80-1839-11e9-9fa6-bbd75621ea2e.png)
> 
> If you need more information, let me know.

are you able to fix?
I have same problem
