### ISSUE TITLE
Android: Animations not triggered

### ISSUE THREAD

**Issue by idlework** [halilb/react-native-textinput-effects#36]
When I install a clean build from the examples on my Android, the animation won't trigger when textinput get's focus. No errors are generated.

I'll try to debug the issue and when I have a solution I'll create a pull request. But does anyone have an idea why this is? Thanks!

Moto G5
Android 7.0

**Comment by halilb** [comment]
Thanks for reporting @idlework!

I just tried this with the example project on Android 4.4 and I don't see any problem. I recently upgraded the example project to react native 0.44, and that might have helped fixing this for me.

Could you pull and re-try with the latest code and let me know?

**Comment by idlework** [comment]
@halilb I found out what it is. The entire animation framework in android debug mode and react-native 0.45 is responding very slow. It was the first animation i put in the app, so it's not your library. My apologies and thanks for the great animations!
