### ISSUE TITLE
Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.

### ISSUE THREAD

**Issue by emiliano-carrillo** [halilb/react-native-textinput-effects#40]
I get this warning whenever I try to run my app using some TextFields but the app doesn't even launch on Expo. Please help.

**Comment by halilb** [comment]
Thanks for reporting @emiliano-carrillo!

I upgraded the example project to react-native 0.44 but couldn't see the message myself. But I changed the code to use ViewPropTypes when it's available. Can you test your project with commit 2ebeba8 and let me know if it fixes the problem?

**Comment by xianglinlin** [comment]
@halilb  I get these warn when I try to npm install yours, please upgrade react-native to 0.46.2 and react  to 16.0.0-alpha.12,  Please help, thanks!

npm WARN kw-react-tween-state@0.1.5 requires a peer of react@^0.14.8 || ^15.0.1 but none was installed.
npm WARN kw-react-tween-state@0.1.5 requires a peer of react-dom@^0.14.8 || ^15.0.1 but none was installed.
npm WARN rc-hammerjs@0.6.8 requires a peer of react@^0.14.3 || ^15.0.0 but none was installed.
npm WARN react-static-container@1.0.1 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 but none was installed.
npm WARN react-sticky@5.0.8 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm WARN react-sticky@5.0.8 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none was installed.
npm WARN recompose@0.23.4 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.

**Comment by halilb** [comment]
This should be fixed in the version `0.4.2`.
