### ISSUE TITLE
how to use icons from '@expo/vector-icons' or custom icons?

### ISSUE THREAD

**Issue by yash2code** [halilb/react-native-textinput-effects#44]

**Comment by halilb** [comment]
I think @expo/vector-icons is the same with react-native-vector-icons. So I believe you can make it run by using the examples in this repo. Let me know if that doesn't work.

This project only supports vector icons for animation, and I chose supporting react-native-vector-icons as it's the most popular library in this field. You can try importing your custom icon font to vector-icons: https://github.com/oblador/react-native-vector-icons#custom-fonts
