### ISSUE TITLE
 underlineColorAndroid not working with kaede

### ISSUE THREAD

**Issue by yash2code** [halilb/react-native-textinput-effects#45]

**Comment by halilb** [comment]
There is a specific line in Kaede to make underlineColorAndroid transparent: https://github.com/halilb/react-native-textinput-effects/blob/master/lib/Kaede.js#L63

`underlineColorAndroid={'transparent'}`

This is required to create original Kaede look and feel: https://tympanus.net/Development/TextInputEffects/

You should fork the repo and modify for your own needs if this doesn't fit with your use case.

**Comment by yash2code** [comment]
@halilb  Yeah I already checked that and its not working , I can see the line even when `underlineColorAndroid={'transparent'}` is set.
