### ISSUE TITLE
Request: Be able to put the icon on the left or the right

### ISSUE THREAD

**Issue by vlw0052** [halilb/react-native-textinput-effects#47]
It'd be nice to be able to put the icons on the left or the right side of the input. 

I'd also gladly contribute to this if you want!

**Comment by halilb** [comment]
Hi @vlw0052, thanks for contributing.

I just wanted to port those animations to react native: https://tympanus.net/Development/TextInputEffects/ And I'm not sure if they'd look good if I make such visual modifications over them.

But I'm always open for a contribution. You're welcome to create a PR, and I can merge them into the project if they look good :)
