### ISSUE TITLE
Example not running

### ISSUE THREAD

**Issue by rochapablo** [halilb/react-native-textinput-effects#48]
@halilb, how do you run the example folder?

I'm getting:

```
error: bundling: UnableToResolveError: Unable to resolve module `react` from `/.../react-native-textinput-effects/lib/Kaede.js`: Module does not exist in the module map
```

I've follow the [instructions](https://github.com/facebook/react-native/issues/4968), but the error keeps going.

Even cleaning **TextInputEffectsExample.js** nothing change.

**Comment by halilb** [comment]
Thanks for reporting @rochapablo.

I just cloned the repository and deployed the example app to iOS simulator. It worked out of the box.

Your problem sounded like a cache problem to me. Did you try removing node_modules and re-installing using `npm install` or `yarn`?

**Comment by rochapablo** [comment]
@halilb, no problem.

Yes, I did that for several times. I'm also running into IOS simulator.

I'll try again.

**Comment by rochapablo** [comment]
@halilb, I'm sorry for the delay. Unfortunately I still having the same problem

![](http://i.imgur.com/rxQi06I.png)

And always running

```
$ rm -rf node_modules
$ npm install
$ npm start -- --reset-cache
$ react-native run-ios
```

**Comment by halilb** [comment]
Could you change package.json and point the registry instead of local file system?

So, change `"react-native-textinput-effects": "file:../",` with `"react-native-textinput-effects": "0.4.0".

**Comment by rochapablo** [comment]
Just did, but still the same problem.

Know what, I did fork to try add the height option to the fields. But  since [I got it](https://github.com/halilb/react-native-textinput-effects/issues/19#issuecomment-318734779) let's close this issue for now and if I got something I let you know.
