### ISSUE TITLE
iOS: Lag while using custom keyboard

### ISSUE THREAD

**Issue by aaveidt** [halilb/react-native-textinput-effects#49]
I'm using Fumi, and it's animation doesn't smooth while using custom keyboard.
With native keyboard, it performs better but i still can see the glitch.

**Comment by halilb** [comment]
Thanks for reporting @Tom29!

I haven't used custom keyboards before. Could you share an example project so I can checkout the problem?

**Comment by Tom29** [comment]
You can use any custom keyboard on Appstore like swiftkey , google keyboard ...
https://itunes.apple.com/us/app/swiftkey-keyboard/id911813648?mt=8

The transition / animation will be blocked while keyboard is loading.

**Comment by halilb** [comment]
Ah, thanks for the info @Tom29. I've never used a custom keyboard on my phone. I'll install one and re-try.

**Comment by halilb** [comment]
This is still the case with Swiftkey after adopting `useNativeDriver` animations. So I don't think we have much to improve the animation performance on our side as those custom keyboards are consuming all the CPU while opening up.

Closing the issue as we don't have a clear fix on our side.
