### ISSUE TITLE
Feature Request: More customisability of colors in Fumi

### ISSUE THREAD

**Issue by huangkaiw3n** [halilb/react-native-textinput-effects#5]
Hi, I've been trying out the Fumi textinput and I think it's really nice. Just wondering if a higher degree of customisability of colors could be added as currently any colors passed in through the props _labelStyle_ and __inputStyle_ are overwritten by their defaults eg:

`<Animated.Text style={[styles.label, labelStyle, {
              fontSize: focusedAnim.interpolate({
                inputRange: [0, 0.7, 0.71, 1],
                outputRange: [16, 16, 12, 12],
              }),
              color: focusedAnim.interpolate({
                inputRange: [0, 0.7],
                outputRange: ['#696969', '#a3a3a3'],
              })`

and

`<TextInput
          ref="input"
          {...this.props}
          style={[styles.textInput, inputStyle, {
            marginLeft: ICON_WIDTH + PADDING,
            color: iconColor,
          }]}`

I think this would be an awesome addition as with that, this textinput field could be used to fit any UI with its beautiful animation and customisability of colors to fit different color themes.

Cheers :)

**Comment by basequatro** [comment]
I like Fumi also, but 2 clicks to change to other field? Did you get this behavior also?

**Comment by huangkaiw3n** [comment]
@basequatro nope. I didn't experience any issues with switching fields

**Comment by basequatro** [comment]
I get this behavior also here. 2 clicks to change field.
https://appetize.io/app/uhgu1wc1htqfcf7bp812gevr2r?device=iphone6s&scale=75&orientation=portrait&osVersion=9.3

**Comment by huangkaiw3n** [comment]
@basequatro ah I think you mean 2 clicks because the keyboard is opened? 1st click closes the keyboard if it's open and the 2nd switches the field. Not sure if it's intended.

Well if you think it should be fixed, you should open a separate issue thread.

**Comment by halilb** [comment]
Thanks for your time and contribution @huangkaiw3n. I'm sorry for my late answer.

Could you check if 7e18820 helps with the issue? I made sure `inputStyle` and `labelStyle` overrides default values. And I added a new prop called `passiveIconColor`.

**Comment by halilb** [comment]
@basequatro That behaviour is related to ScrollView. Try setting ScrollView's `keyboardShouldPersistTaps` property to `true`.

**Comment by huangkaiw3n** [comment]
@halilb Yeap. 7e1882064dedf3449db8c29c40c5f2f78b727c99 allows customising the input text color with prop `inputStyle`, the label text color with `labelStyle`, as well as the initial icon color using `passiveIconColor`. Thanks for the awesome library. Update it on npm soon will ya 👍
