### ISSUE TITLE
TextInput secureTextEntry

### ISSUE THREAD

**Issue by hdhc44** [halilb/react-native-textinput-effects#50]
anyway i was trying to make your custom input as secrueTextEntry to make it as password input
but for example

 ` <Fumi
            label={'Password'}
            labelStyle={{ color: '#58595B' }}
            inputStyle={{ color: '#f95a25' }}
            iconClass={FontAwesomeIcon}
            iconColor={'#f95a25'}
            iconSize={15}
            secureTextEntry={true}
          />`

this way didnt work so i look into your js(fumi.js) file
added password to the `const{}.this.props` and to `static propTypes` as bool
and then under the `underlineColorAndroid` added  `secureTextEntry={password}`

i dont know why this way worked but it worked anyway with no error
i want you to add this(passwordInput) to this awesome custom input  

idk why but if i do that it's kinda laggy on android

Thank you and have a good day

**Comment by halilb** [comment]
Thanks for reporting @hdhc44!

#52 is similar with this one. Let's track the problem in that issue.
