### ISSUE TITLE
Icon appearing left in Kohana

### ISSUE THREAD

**Issue by mbarbier003** [halilb/react-native-textinput-effects#51]
Hi, and thanks for the great component ! 
I noticed a display issue in the Kohana component with the 'envelope' icon from FontAwesomeIcon.
I did not try more icons, the 'key' one works well.
Here you can see the problem : 

![20542780_10211835568297357_1219304175_o](https://user-images.githubusercontent.com/22587439/28774948-f235412a-75ef-11e7-9580-bf5638d5dcd0.jpg)

The icon still appears a little when the TouchableWithoutFeedback is not touched.
I modified the 
`transform: [
                {
                  translateX: focusedAnim.interpolate({
                    inputRange: [0, 1],
                    outputRange: [-15 - iconSize, 0],
                  }),
                },
              ]`
from `Kohana.js`
to : 
`transform: [
                {
                  translateX: focusedAnim.interpolate({
                    inputRange: [0, 1],
                    outputRange: [-20 - iconSize, 0],
                  }),
                },
              ]`
and it seems to work. But I don't want to have to modify the Kohana.js as I will likely export the project and my coworkers will `npm install` without this change made.
I'm not sure my change works on all icons though.
Thanks

**Comment by halilb** [comment]
Hi @mbarbier003, thanks for reporting!

You can always fork the repo and make your changes there, and you can point that repo in your package.json file.

Meanwhile, we can try finding an appropriate way to fix the issue for everyone.

**Comment by mbarbier003** [comment]
Hi @halilb,
I will fork and point to my repo until you find and release a suitable long-term solution :)
Thanks

**Comment by RiusmaX** [comment]
+1 for the modification
