### ISSUE TITLE
Hoshi label to shrink when moving up

### ISSUE THREAD

**Issue by MeganGilligan1** [halilb/react-native-textinput-effects#55]
Hi, 
Just wondering if there is a way to get the label to shrink/change colour when it moves up to the top?

**Comment by halilb** [comment]
Hi @MeganGilligan1,

There is only position animation over the label in Hoshi. You can try forking and customising the label simply by adding fontSize and color animations.

Here is an example for fontSize. You can make it better by tinkering the numbers.

```
<Animated.Text style={[styles.label, labelStyle, {
  fontSize: focusedAnim.interpolate({
    inputRange: [0, 0.5, 1],
    outputRange: [16, 18, 20],
   }),
}]}>
  {label}
</Animated.Text>
```

Let me know if you have any questions.
