### ISSUE TITLE
keyType doesn't work

### ISSUE THREAD

**Issue by 2hyjun** [halilb/react-native-textinput-effects#56]
I set property as keyType="decimal-pad" or keyType={"decimal-pad"} or 'number-pad', 'numeric'..
it doesn't works on Fumi with iphone simulator iphone7, android.

This problem appears only on me?

**Comment by PR1YANKPAT3L** [comment]
@2hyjun The correct syntax is **keyboardType='decimal-pad'**. If you wish to change the way return key looks, then you need to use **returnKeyType='next'** for example. 


**Options for keyboardType**
`keyboardType?: enum('default', 'email-address', 'numeric', 'phone-pad', 'ascii-capable', 'numbers-and-punctuation', 'url', 'number-pad', 'name-phone-pad', 'decimal-pad', 'twitter', 'web-search') `

**Options for returnKeyType**
`returnKeyType?: enum('done', 'go', 'next', 'search', 'send', 'none', 'previous', 'default', 'emergency-call', 'google', 'join', 'route', 'yahoo') `

You can find detailed information about various props: [RN TextInput](https://facebook.github.io/react-native/docs/textinput.html)

**Comment by halilb** [comment]
@PR1YANKPAT3L is definitely right. `keyboardType={'decimal-pad'}` works fine with Fumi.
