### ISSUE TITLE
Fonts referenced in templates

### ISSUE THREAD

**Issue by chongdog83** [halilb/react-native-textinput-effects#58]
Got a font family error when I used the Madoka template.

When I removed fontFamily: 'Arial', from /lib/Madoka.js, it uses my default font and no error.

label: {
backgroundColor: 'transparent',
fontFamily: 'Arial',
fontWeight: 'bold',
color: '#6a7989',
},

**Comment by johanbuys** [comment]
Hi, had the same issue. 

You can override the labelStyles like so 

`        labelStyle={{
          fontFamily: 'LiberationSans-Regular',
        }}`
Here LiberationSans-Regular is loaded as a custom font by my app. It is an alternative to Arial, use any custom font you want. 

Hope this helps.

**Comment by halilb** [comment]
@johanbuys is right. It should work when you use a fontFamily in `labelStyle` prop.

I tested and can confirm this works on iOS:

````
 <Madoka
    style={styles.input}
    label={'Frequency'}
    borderColor={'#aee2c9'}
    labelStyle={{ color: '#008445' }}
    inputStyle={{
      color: '#f4a197',
      fontFamily: 'AmericanTypewriter-CondensedBold',
    }}
/>
```

Let me know if you still have a problem with this.
