### ISSUE TITLE
Version bump to fix propTypes issue

### ISSUE THREAD

**Issue by guilhermepontes** [halilb/react-native-textinput-effects#59]
Hello @halilb, nice work here! 
Can create a new release (`0.4.1`) so we can have the fix for the propTypes error?

Thank you.

**Comment by THPubs** [comment]
With the new React `16.0.0` this package breaks.

**Comment by joelcdoyle** [comment]
```Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead.```

BaseInput and Kaede are included in stack trace.

**Comment by halilb** [comment]
I pushed version `0.4.1` to npm. Could you confirm if it fixes the problem @guilhermepontes @THPubs @joelcdoyle?

**Comment by RyszardRzepa** [comment]
"react-native-textinput-effects": "^0.4.1", version still has warning about View.propTypes.style.
In new React 16.beta.5, the app will crash.

**Comment by halilb** [comment]
I published version `0.4.2` and can confirm it's working with react-native version `0.50.0`.
