### ISSUE TITLE
<Sae /> throws error

### ISSUE THREAD

**Issue by devhyunjae** [halilb/react-native-textinput-effects#60]
```
<View>
          <Kaede />
          <Hoshi />
          <Jiro />
          <Isao />
          <Madoka />
          <Akira />
          <Sae />
</View>
```

until `Akira` works fine, but `Sae` shows this error

<img width="372" alt="screen shot 2017-09-07 at 11 51 47 am" src="https://user-images.githubusercontent.com/12890257/30145299-10b8b6cc-93c3-11e7-8d54-aa724992eefc.png">

**Comment by stirman** [comment]
+1 Getting same error and Sae is the style I would love to use!

**Comment by stirman** [comment]
@devhyunjae Were you able to find a fix or workaround? Thx!

**Comment by adrianveracom** [comment]
This is still happening. Basically Sae is broken for me too.

**Comment by nertilzhuri** [comment]
I had the same error, it appears that Sae does not work without icons, so if you add:
iconClass={FontAwesomeIcon}
iconName={'pencil'}
iconColor={'white'}
it will work as it is intended.

**Comment by halilb** [comment]
@nertilzhuri is right. Sae needs `iconClass` prop to work.
