### ISSUE TITLE
Tap icon to set focus, open form

### ISSUE THREAD

**Issue by stirman** [halilb/react-native-textinput-effects#62]
Using Sae with pencil icon similar to example. To open the textinput user must tap the label, tapping on the icon does nothing, but the icon looks like the button to tap to start editing. Not sure how to wire in that functionality... or, am I missing something?

Thanks!

**Comment by halilb** [comment]
Thanks for reporting @stirman.

I just fixed this in d61b8fa. I am going to publish version `0.4.2` which will be including this commit.
