### ISSUE TITLE
Effect not apply if  both (username and Password) get value from cache or cookie 

### ISSUE THREAD

**Issue by jaykhatri90165** [halilb/react-native-textinput-effects#66]
Hello Sir,

i am using text-input-effect and i got some issues like when multi inputs take value from cache or cookie, 
at that time effect apply only first input only its ignore the second input which input type is password.

its happen when i am doing normal refresh(f5), with hard refresh (ctrl + f5) its working fine.

Please help 
Thank you .

**Comment by halilb** [comment]
Are you sure this is the right repository @jaykhatri90165?

This is a react-native library and we don't have f5 or ctrl + f5 in react-native environment.
