### ISSUE TITLE
How to return my input below when i close the Keyboard?

### ISSUE THREAD

**Issue by phantoxe** [halilb/react-native-textinput-effects#67]
Hi folks...

When i click in my Hoshi input the object go up... perfect... but when i close the keyboard all the objects should not go back down?

Thanks

**Comment by halilb** [comment]
Thanks for reporting @phantoxe.

What you're describing is the nature of text inputs in this library. The animation will go back if the text input is empty. And it will preserve it's state when users enters some value.
