### ISSUE TITLE
is it possible to change label size

### ISSUE THREAD

**Issue by bohrend** [halilb/react-native-textinput-effects#69]
Not sure if its a bug, maybe just a feature request, but I have tried fontSize on labelStyle

**Comment by halilb** [comment]
Thanks for reporting @bohrend.

You can change fontSize for most of the inputs  by setting `fontSize` field of `labelStyle`. But that might not work on some of the inputs as they are overriding `fontSize` for the animation. In that case, I'd advise to fork the library and modify fontSize values within the text input file you're using.

Let me know if it doesn't work out for you.
