### ISSUE TITLE
Margin between label and input text on Hoshi

### ISSUE THREAD

**Issue by nicolasdelfino** [halilb/react-native-textinput-effects#7]
Hi, I can´t seem to edit the "active state" position of the label on Hoshi, 

Problem is Im´using a large font (25), my dummy text on the label looks great but when
I select the input field the dummy label seems to animate up the same amount as if I were using a small font, rendering it almost on top of the input field text.

Would need to edit the label offset on active.

**Comment by 7Style** [comment]
You can use prop "height".

**Comment by halilb** [comment]
Hi @nicolasdelfino!

@7Style is right. You can tweak `height` and `inputStyle` props to get a better result. Something like this would do the job:

```
<Hoshi
  label={'Town'}
  borderColor={'#b76c94'}
  maskColor={'#F9F7F6'}
  height={60}
  labelStyle={{ fontSize: 25 }}
  inputStyle={{ bottom: -8 }}
/>
```

Let me know if it doesn't work out.
