### ISSUE TITLE
autoCapitalize Not Working 

### ISSUE THREAD

**Issue by ZainaliSyed** [halilb/react-native-textinput-effects#73]
<Hoshi
            value={value}
            maxLength={21}
            ref={"eventName"}
            labelStyle={this.state.eventStyle}
            returnKeyType="done"
            **autoCapitalize="words"**
            borderColor={Colors.transparent}
            onChangeText={onChangeText}
            keyboardType="name-phone-pad"
          /> @halilb

**Comment by halilb** [comment]
Thanks for reporting @ZainaliSyed!

The library is just passing those props to TextInput. So, you should look for answers why TextInput is not acting correctly with that prop. Let me know if it's working on a regular TextInput and not working on Hoshi.
