### ISSUE TITLE
Hide Icon

### ISSUE THREAD

**Issue by valeriaabo** [halilb/react-native-textinput-effects#74]
What if I want to use Fumi, but I want it without the icon?
I try to use it but it leaves me a blank space, I cant remove it.
Any ideas?

**Comment by alyssaong1** [comment]
+1

**Comment by halilb** [comment]
I guess the only way to achieve this is setting `iconColor` and `passiveIconColor` props the same color with the background.

Example:

```
<Fumi
    style={{ backgroundColor: 'white' }}
    label={'Course Name'}
    labelStyle={{ color: '#a3a3a3' }}
    inputStyle={{ color: '#f95a25' }}
    iconClass={FontAwesomeIcon}
    iconName={'university'}
    iconColor={'white'}
    passiveIconColor={'white'}
    iconSize={15}
/>
```

If you'd like more customization like removing the separator, I suggest you forking the library and making direct edits to the component.
