### ISSUE TITLE
Unable to display the icon inside text input fields

### ISSUE THREAD

**Issue by MrChinmaya** [halilb/react-native-textinput-effects#75]
I had imported vector icons lib but also unable to display the icons.

import FontAwesomeIcon from 'react-native-vector-icons/FontAwesome';
import Icon from 'react-native-vector-icons/FontAwesome';
import { Sae   } from 'react-native-textinput-effects';

 <Sae
    label={'Email Address'}
    iconClass={FontAwesomeIcon}
    iconName={'pencil'}
    iconColor={'white'}
    // TextInput props
    autoCapitalize={'none'}
    autoCorrect={false}
  />

**Comment by halilb** [comment]
Could you check if you can render icons directly in your screen @MrChinmaya? The code block you posted works just fine on the example project.
