### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by Jta26** [halilb/react-native-textinput-effects#77]
Im trying to use this, but I have absolutely no idea what causes the prop to be undefined. Here is the stack trace.

12-11 23:55:07.601 14408 14500 E ReactNativeJS: TypeError: undefined is not an object (evaluating 'Component.__propTypesSecretDontUseThesePlease')
12-11 23:55:07.601 14408 14500 E ReactNativeJS: 
12-11 23:55:07.601 14408 14500 E ReactNativeJS: This error is located at:
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in Sae (at App.js:24)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in RCTView (at View.js:112)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in View (at App.js:19)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in SignIn (at SceneView.js:31)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in SceneView (at CardStack.js:394)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in RCTView (at View.js:112)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in View (at CardStack.js:393)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in RCTView (at View.js:112)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in View (at CardStack.js:392)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in RCTView (at View.js:112)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in View (at createAnimatedComponent.js:134)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in AnimatedComponent (at Card.js:26)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in Card (at PointerEventsContainer.js:55)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in Container (at CardStack.js:436)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in RCTView (at View.js:112)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in View (at CardStack.js:365)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in RCTView (at View.js:112)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in View (at CardStack.js:364)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in CardStack (at CardStackTransitioner.js:97)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in RCTView (at View.js:112)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in View (at Transitioner.js:187)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in Transitioner (at CardStackTransitioner.js:49)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in CardStackTransitioner (at StackNavigator.js:60)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in Unknown (at createNavigator.js:52)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in Navigator (at createNavigationContainer.js:216)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in NavigationContainer (at renderApplication.js:35)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in RCTView (at View.js:112)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in View (at AppContainer.js:102)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in RCTView (at View.js:112)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in View (at AppContainer.js:122)
12-11 23:55:07.601 14408 14500 E ReactNativeJS:     in AppContainer (at renderApplication.js:34)

**Comment by halilb** [comment]
I'm glad you figured it out @Jta26.
