### ISSUE TITLE
Components doesn't show properly without ScrollView

### ISSUE THREAD

**Issue by SaveYourTime** [halilb/react-native-textinput-effects#79]
![img_5081](https://user-images.githubusercontent.com/35715664/35953090-f07abed6-0cbd-11e8-8415-86ebb05f8254.PNG)
<img width="681" alt="2018-02-08 10 47 01" src="https://user-images.githubusercontent.com/35715664/35953077-e82bc1d0-0cbd-11e8-80e8-0894ab66621a.png">

TextInput will cuddle up in a heap after I took the ScrollView off.

**Comment by DominikVavra** [comment]
Same here

**Comment by SaveYourTime** [comment]
@DominikVavra This library seems not to be maintained anymore...

**Comment by LPAnglers** [comment]
<ScrollView scrollEnabled={false}> Use this and ScrollView will not be moved

**Comment by halilb** [comment]
Fixed with #79.
