### ISSUE TITLE
how to get value input with ref

### ISSUE THREAD

**Issue by nguyenvanphuc2203** [halilb/react-native-textinput-effects#81]
console.log(this.refs.sdt._lastNativeText)
>> undefined

<Kohana
            style={{ backgroundColor: '#f9f5ed',marginTop:3 }}
            label={'Username'}
            iconClass={Icon}
            iconName={'user'}
            iconColor={'#f4d29a'}
            labelStyle={{ color: '#91627b' }}
            inputStyle={{ color: '#91627b' }}
            useNativeDriver
            ref="sdt"
            keyboardType="numeric"
          />

**Comment by erspark2002** [comment]
The <TextInput> used internally already has a ref prop set to "input". You can't assign your own ref. This is a major oversight in the design. You can't focus a specified input.

I can't use this library until it's fixed.

**Comment by halilb** [comment]
Thanks for the answer @erspark2002.
