### ISSUE TITLE
onFocus not working

### ISSUE THREAD

**Issue by brunoczo** [halilb/react-native-textinput-effects#83]
I'm trying to use onfocus, but it does not work on the Jiro component. Is it possible to use onfocus? In the 
TextInput component the onfocus works perfectly.

**Comment by halilb** [comment]
The following code works perfect for me on iOS @brunoczo:

```
<Jiro
  label={"Dog's name"}
  borderColor={'#9b537a'}
  inputStyle={{ color: 'white' }}
  onFocus={() => console.log('onfocus')}
/>
```

Please post more information like react-native version, library version, platform, and the code block you are trying to run.
