### ISSUE TITLE
Unable to override border size and color in Hoshi

### ISSUE THREAD

**Issue by zamiang** [halilb/react-native-textinput-effects#9]
Looks like it could be fixed by swapping the order of `containerStyle` and `styles.container` here: https://github.com/halilb/react-native-textinput-effects/blob/master/lib/Hoshi.js#L51

**Comment by halilb** [comment]
Thanks for reporting @zamiang!

I changed the order of styles. It's available in version `0.2.0`.

Closing the issue now but feel free to re-open if it doesn't fix the problem.
