### ISSUE TITLE
Feature Request: Placeholder Text Color

### ISSUE THREAD

**Issue by wizebin** [halilb/react-native-textinput-effects#91]
## Feature Request Description

Currently as a consumer of this library I have no way to control the placeholder color of the input field

#### Code

Something as simple as this would get the job done (sample from the fumi class)

           <Animated.Text
              style={[
                styles.label,
                {
                  fontSize: focusedAnim.interpolate({
                    inputRange: [0, 0.7, 0.71, 1],
                    outputRange: [16, 16, 12, 12],
                  }),
                  color: focusedAnim.interpolate({
                    inputRange: [0, 0.7],
                    outputRange: [placeholderColor || '#696969', placeholderComposite || '#a3a3a3'],
                  }),
                },
                labelStyle,
              ]}
            >

The new props could be something along the lines of the `placeholderColor` and `placeholderComposite` that I've added in this sample.

#### Reasoning

I would like to validate my user's input and indicate missing fields with a simple color change, currently I can add a different style like a border color, but a placeholder color would be slightly better.

<img width="396" alt="screen shot 2019-02-10 at 9 32 23 pm" src="https://user-images.githubusercontent.com/18584095/52534348-7fced700-2d7b-11e9-9ff4-5e3366724457.png">
<img width="392" alt="screen shot 2019-02-10 at 9 32 35 pm" src="https://user-images.githubusercontent.com/18584095/52534349-80676d80-2d7b-11e9-9ef5-f3010631499c.png">

#### Alternative

Having a custom placeholder component would fulfill this need

https://github.com/halilb/react-native-textinput-effects/issues/12

**Comment by wizebin** [comment]
Nope, I'm crazy, missed the labelStyle prop- that suits my needs just fine!

**Comment by halilb** [comment]
I'm glad you figured it out @wizebin :)
