### ISSUE TITLE
onChangeText

### ISSUE THREAD

**Issue by CuongTran69** [halilb/react-native-textinput-effects#97]
How I can use event onChangeText() :(

**Comment by simransinghkataria** [comment]
There is a property on change you can see the below code for reference

```
this.state={
ac_username : null
}
onChangeText={ 
  (ac_username) => { 
    this.setState( {ac_username} ) 
  } 
}
```

**Comment by halilb** [comment]
You can directly use react-native TextInput props @CuongTran69, just like @simransinghkataria has posted.

You can read more about it in react-native documentation: https://twitter.com/davidwalshblog/status/1109993816365428736
